- client/src/api/authAPI.tsx
- client/src/interfaces/UserData.tsx
- client/src/interfaces/UserLogin.tsx
Updated AuthAPI.tsx, UserData.tsx,Userlogin,tsx, Login.ts & Auth.ts on client side.
> Added LoginPage Feature Branch

- client/package-lock.json
- client/package.json
Dealt with merge conflicts that were creating errors in the package-lock.json files.
> handled merge conflicts in package-lock.json and package.json

- client/src/api/authAPI.tsx
- client/src/api/userAPI.tsx
- client/src/components/Navbar.tsx
- client/src/interfaces/RegisterUser.tsx
- client/src/pages/Login.tsx
- client/src/pages/Register.tsx
- client/src/utils/Auth.ts
- server/src/routes/auth-routes.ts
Updated client side pages.  Added a register page ( possibly going to create this instead of having the ability to login AND register on the same page) 
Updated client side authAPI.tsx
Added a register function that'll fetch from the back-end.  Still need to update some back-end information in order to get this functioning, but it's a start.
Updated server side routes.  Added an auth-routes.ts within the api folder.  Still need to expand within the api folder including multiple routes to the various pages.
> Minor Updates

- client/package-lock.json
- server/src/middleware/auth.ts
Added middle ware function to handle JWT validation allowing user to access website.
> Added authentication middleware to handle JWT validation

- client/src/pages/Register.tsx
Register.tsx page on the front-end should be able to handle registration (if I didn't make any mistakes).  I can look into updating a backend route to handle sending the emails via the resend API.
> added .env file in server folder.  Updated Register.tsx page on the client side

- .gitignore
- server/package-lock.json
- server/package.json
- server/src/controllers/reservation-controller.ts
- server/src/controllers/time-slot-controller.ts
- server/src/models/Reservation.ts
- server/src/models/TimeSlot.ts
- server/src/models/index.ts
- server/src/routes/api/index.ts
- server/src/routes/api/reservation-routes.ts
- server/src/routes/api/time-slot-routes.ts
- server/src/routes/api/user-routes.ts
This PR refactors the sequelize models to remove the seating model entirely. All of the capacity tracking is entirely contained in the timeslot table. Additionally, all of the time data is contained in the timeslot table which is related to the reservation object.
> server/db-logic/refactor/anthony - Refactor of DB Models and CRUD

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/api/reservationAPI.tsx
- client/src/api/timeslotAPI.tsx
- client/src/components/Navbar.tsx
- client/src/main.tsx
- client/src/pages/Home.tsx
- client/src/pages/Reservation.tsx
- client/src/utils/dateUtils.ts
This PR modifies main.tsx and App.tsx to provide basic routing.
It adds Reservation.tsx logic for retrieval of timeslots. This logic is not complete and currently logs to console.
> client/reservations/anthony - Modified main.tsx / App.tsx | Added Reservation.tsx logic

- client/src/api/reservationAPI.tsx
- client/src/api/timeslotAPI.tsx
- client/src/components/ReservationForm.tsx
- client/src/interfaces/ReservationData.tsx
- client/src/main.tsx
- client/src/pages/CreateReservation.tsx
- client/src/pages/Reservation.tsx
- package-lock.json
Contains base logic for pulling available time slots, and click through to create reservation page with stateful slotId parameter.
> client/reservations/anthony - Reservations page and Create Reservations Page

- client/package-lock.json
- client/package.json
Added react router dom to the dependencies to fix bug in Register page.
> added-react-router-dom-to-dependencies

- client/src/main.tsx
Added a route on main.tsx to send to contact page.
> added route to contact on main.tsx

- client/src/main.tsx
- client/src/pages/Menu.Tsx
Added a route to the menu page on main.tsx and corrected syntax error on Menu page filename preventing render.
> added route to menu page on main.tsx

- client/src/pages/Menu.Tsx
Added some foundational content to the menu page to be built off of in the future.
> Added some basic content to menu page

- client/src/App.tsx
- client/src/components/Header.tsx
Added Header component to the application.
> Header component

- server/src/models/User.ts
- server/src/seeds/index.ts
This PR fixes some bugs with the User model not correctly populating columns in the table.
> fixes for user model not correctly populating table columns

- client/src/App.tsx
- client/src/components/ReservationForm.tsx
- client/src/main.tsx
- client/src/pages/Confirmation.tsx
- client/src/pages/Contact.tsx
- client/src/pages/Home.tsx
- client/src/pages/Menu.tsx
- client/src/pages/Reservation.tsx
Added a confirmation page for a successful reservation. Removed some erroneous .css references and moved the css reference to App.tsx.
> confirmation page for reservation, updated css references to App.tsx

- client/src/pages/Login.tsx
- client/src/styles/Login.css
Added css styling to login page.
> added styling to login page

- client/src/pages/Register.tsx
- client/src/styles/Register.css
Added styling to register page.
> added styling to the register page

- client/src/pages/Reservation.tsx
- client/src/styles/Reservation.css
Added css styling to reservation.
> Reservation styling

- server/src/models/User.ts
- server/src/routes/auth-routes.ts
This PR fixes a bug that occurs when the reservation is created. The user hashed password was being re-hashed.
> bug fix for hashing hashes on reservation issue

- server/src/server.ts
This PR adds proper production path tracking and a route for direct endpoint typing into the URL bar.
> bugfix for routing issues in production

- server/src/server.ts
"fixed" route order in server.ts
> "fixed" route order in server.ts

- client/src/components/Header.tsx
> dot practice

- client/src/styles/Contact.css
- client/src/styles/Home.css
Fixed the pathways for images so that they may be rendered properly.
> fixed image path to display on render
